name: isbe-catalog-ui

services:
  catalog-ui:
    image: in2workspace/bae-frontend:v0.0.0
    container_name: isbe-catalog-ui
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: always
