export const environment = {
    BASE_URL: 'https://tmf.evidenceledger.eu/tmf-api/productCatalogManagement/v4',
    PAYMENT_URL: '',
    ISBE_CATALOGUE: true,
    LEGACY_PREFIX: '/ux',
    PRODUCT_CATALOG: '/catalog',
    SERVICE: '/service',
    RESOURCE: '/resource',
    PRODUCT_SPEC: '/productSpecification',
    SERVICE_SPEC: '/serviceSpecification',
    RESOURCE_SPEC: '/resourceSpecification',
    CUSTOMER_BILLING:'/appliedCustomerBillingRate',

    ACCOUNT: '/account',
    SHOPPING_CART: '/shoppingCart',
    INVENTORY: '/inventory',
    PRODUCT_ORDER: '/ordering',
    BILLING: '/billing',
    CHARGING: '/charging',

    CONSUMER_BILLING_URL: '',
    INVOICE_LIMIT: 100,

    PRODUCT_LIMIT: 6,
    CATALOG_LIMIT: 8,
    INVENTORY_LIMIT: 6,
    INVENTORY_RES_LIMIT: 8,
    INVENTORY_SERV_LIMIT: 8,
    PROD_SPEC_LIMIT: 6,
    USAGE_SPEC_LIMIT: 6,
    ORDER_LIMIT: 1000,
    CATEGORY_LIMIT: 100,
    SIOP: true,
    TAX_RATE: 20,
    AUTH_MODE: 'oidc',
    SIOP_INFO: {
        enabled: false,
        isRedirection: false,
        pollPath: "",
        pollCertPath: "",
        clientID: "https://catalog.redisbe.com",
        callbackURL: "",
        verifierHost: "",
        verifierQRCodePath: "",
        requestUri: ""
    },
    MATOMO_TRACKER_URL: "",
    MATOMO_SITE_ID: "",
    TICKETING_SYSTEM_URL: "",
    KNOWLEDGE_BASE_URL: "",
    KB_ONBOARDING_GUIDELINES_URL: "",
    KB_GUIDELNES_URL:"",
    REGISTRATION_FORM_URL: "",
    SEARCH_ENABLED: true,
    PURCHASE_ENABLED: false,
    ISBE_TRUST_LINK: "",
    ISBE_ABOUT_LINK: '',
    ISBE_REGISTER_LINK: '',
    ISBE_PUBLISH_LINK:'',
    ISBE_LINKEDIN: 'https://www.linkedin.com/company/redisbe/posts/?feedView=all',
    ISBE_YOUTUBE: 'https://www.youtube.com/@REDISBE',
    ISBE_X: 'https://x.com/REDISBE',
    BUNDLE_ENABLED: false,
    DFT_CATALOG_ID: '',
    MAX_FILE_SIZE:3145728,
    SCOPE: "openid eidas",
    RESPONSE_TYPE: 'code',
    AUTHORITY: "https://certauth.evidenceledger.eu",
    REDIRECT_URL: "https://deploy-preview-2--isbecatalog.netlify.app/",
    POST_LOGIN_ROUTE: '/dashboard'

};
