
export const environment = {
    DEV_ACCESS_TOKEN: "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICItckxwSkhNVkhCSUQ0Q2FRX0dsTjhFTEprQ0tYMUJWUzhMTzd6enU1cTFVIn0.eyJleHAiOjE3NzcyMDU4NjYsImlhdCI6MTc3NDg1MDUwMSwiYXV0aF90aW1lIjoxNzc0NjEzODY2LCJqdGkiOiJvbnJ0YWM6NDNiYmQxNDctODcxMS01MmUyLTU3NWUtN2M2OTc1ZjMwNWM4IiwiaXNzIjoiaHR0cHM6Ly9pZHAuZGV2LmNsb3VkLXcuZW52cy5yZWRpc2JlLmNvbS9hdXRoL3JlYWxtcy9kZXYtaXNiZSIsImF1ZCI6WyJpc2JlLXBvcnRhbC1kZXYiLCJhY2NvdW50Il0sInN1YiI6ImIyMzQ5ZTMxLWEyOTktNGU5Yi04ZGQxLWQxMWExZDFmNzBjMSIsInR5cCI6IkJlYXJlciIsImF6cCI6Imh0dHBzOi8vY2F0YWxvZy5pc2Jlb25ib2FyZC5jb20iLCJzaWQiOiIyMTQyZThmMC0zZTFiLTkwZjEtZjQxNC0wOWIwMjM0MjIyMTEiLCJhY3IiOiIwIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHBzOi8vY2F0YWxvZy5kZXYuY2xvdWQtdy5lbnZzLnJlZGlzYmUuY29tIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLWRldi1pc2JlIiwib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIG9yZ2FuaXphdGlvbiBlbWFpbCBwcm9maWxlIiwidXNlcl9pZGVudGlmaWVyIjoiMTIzNDU2NzhBIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm9yZ2FuaXphdGlvbiI6IkFMQVNUUklBIiwibmFtZSI6IkpvaG4gRG9lIiwib3JnYW5pemF0aW9uX2lkZW50aWZpZXIiOiJWQVRFUy1HODc5MzYxNTkiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJqZXN1c0BhbGFzdHJpYS5pbyIsInBvd2VyIjpbeyJhY3Rpb24iOlsiKiJdLCJkb21haW4iOiJJU0JFIiwiZnVuY3Rpb24iOiJNYW5hZ2VtZW50IiwidHlwZSI6Im9yZ2FuaXphdGlvbiJ9LHsiYWN0aW9uIjpbIioiXSwiZG9tYWluIjoiSVNCRSIsImZ1bmN0aW9uIjoiSGVscGRlc2siLCJ0eXBlIjoib3JnYW5pemF0aW9uIn0seyJhY3Rpb24iOlsiKiJdLCJkb21haW4iOiJJU0JFIiwiZnVuY3Rpb24iOiJGYXVjZXQiLCJ0eXBlIjoib3JnYW5pemF0aW9uIn0seyJhY3Rpb24iOlsiKiJdLCJkb21haW4iOiJJU0JFIiwiZnVuY3Rpb24iOiJXaXphcmQiLCJ0eXBlIjoib3JnYW5pemF0aW9uIn0seyJhY3Rpb24iOlsiKiJdLCJkb21haW4iOiJJU0JFIiwiZnVuY3Rpb24iOiJOb3Rhcml6YXRpb24iLCJ0eXBlIjoib3JnYW5pemF0aW9uIn0seyJhY3Rpb24iOlsiKiJdLCJkb21haW4iOiJJU0JFIiwiZnVuY3Rpb24iOiJOb3RpZmljYXRpb25zIiwidHlwZSI6Im9yZ2FuaXphdGlvbiJ9LHsiYWN0aW9uIjpbIioiXSwiZG9tYWluIjoiSVNCRSIsImZ1bmN0aW9uIjoiSWRlbnRpdHkiLCJ0eXBlIjoib3JnYW5pemF0aW9uIn0seyJhY3Rpb24iOlsiKiJdLCJkb21haW4iOiJJU0JFIiwiZnVuY3Rpb24iOiJFbnJvbGxtZW50IiwidHlwZSI6Im9yZ2FuaXphdGlvbiJ9LHsiYWN0aW9uIjpbIkV4ZWN1dGUiXSwiZG9tYWluIjoiSVNCRSIsImZ1bmN0aW9uIjoiT25ib2FyZGluZyIsInR5cGUiOiJvcmdhbml6YXRpb24ifV0sImdpdmVuX25hbWUiOiJKb2huIiwidXNlciI6IkpvaG4gRG9lIiwiZmFtaWx5X25hbWUiOiJEb2UiLCJlbWFpbCI6Imhlc3VzLnJ1aXpAZ21haWwuY29tIn0.a__P_BHOhBqHyetIgFLO2zMy63X8Ul6Fxx-zS3SlsB-X_tL-wP0r8H-cLoRKactjoKqbx5EVCrT0I5DE1BrWbS492vSgcyEVOcV334Tfndw57FwslU5OA3W-teDqkQPHJnbnWGb7WyO4h81xnLZFf-Ymgg0Ho3Cmgjn0TctjnPMzHcpEjw9h1_A-uzN0XBdK-cApsbk2y2ywY8kTS7HjZ221zW7Rgzs9ftB3-jodxOSStl8ygOQZ3Iy9P-txMP8_cNMlV4ggKgD6kHDlzRp87TFS1nKcDHG2aX_XJAXICWn2wcTN6G7-x7urMvNWj6kSJb98vjLbllg0BIAQenhfsQ",
    BASE_URL: 'https://tmf.evidenceledger.eu/tmf-api/',
    FOUNDATION_ID: 'VATES-G87936159',
    locale: 'es-ES',
    PRODUCT_CATALOG_MANAGEMENT_URL: 'productCatalogManagement/v4',
    PARTY_URL: 'party/v4',
    PAYMENT_URL: '',
    ISBE_CATALOGUE: true,
    LEGACY_PREFIX: '',
    ORGANIZATION: '/organization',
    INDIVIDUAL: '/individual',
    PRODUCT_CATALOG: '/catalog',
    SERVICE: '/service',
    RESOURCE: '/resource',
    PRODUCT_SPEC: '/productSpecification',
    SERVICE_SPEC: '/serviceSpecification',
    RESOURCE_SPEC: '/resourceSpecification',
    ACCOUNT: '/account',
    SHOPPING_CART: '/shoppingCart',
    INVENTORY: '/inventory',
    PRODUCT_ORDER: '/ordering',
    CHARGING: '/charging',
    BILLING: '/billing',
    CUSTOMER_BILLING:'/appliedCustomerBillingRate',
    CONSUMER_BILLING_URL: '',
    PRODUCT_LIMIT: 6,
    CATALOG_LIMIT: 8,
    INVENTORY_LIMIT: 6,
    INVENTORY_RES_LIMIT: 6,
    INVENTORY_SERV_LIMIT: 6,
    PROD_SPEC_LIMIT: 6,
    USAGE_SPEC_LIMIT: 6,
    ORDER_LIMIT: 1000,
    CATEGORY_LIMIT: 100,
    INVOICE_LIMIT: 100,
    SIOP: false,
    TAX_RATE: 20,
    AUTH_MODE: 'oidc',
    SIOP_INFO: {
        enabled: true,
        isRedirection: true,
        pollPath: "",
        pollCertPath: "",
        clientID: "https://catalog.isbeonboard.com",
        callbackURL: "http://localhost:4200/dashboard",
        verifierHost: "https://verifier.dome-marketplace-sbx.org",
        verifierQRCodePath: '/oidc/authorize',
        requestUri: "https://verifier.dome-marketplace-sbx.org/oid4vp/auth-request"
    },
    MATOMO_TRACKER_URL: "",
    MATOMO_SITE_ID: "",
    TICKETING_SYSTEM_URL: "",
    KNOWLEDGE_BASE_URL: "",
    KB_ONBOARDING_GUIDELINES_URL: "",
    KB_GUIDELNES_URL:"",
    REGISTRATION_FORM_URL: "https://onboard-dev.redisbe.com/",
    SEARCH_ENABLED: false,
    PURCHASE_ENABLED: false,
    ISBE_TRUST_LINK: "",
    ISBE_ABOUT_LINK: 'https://redisbe.com/',
    ISBE_REGISTER_LINK: 'https://onboard-dev.redisbe.com/',
    ISBE_PUBLISH_LINK:'',
    ISBE_LINKEDIN: 'https://www.linkedin.com/company/redisbe/posts/?feedView=all',
    ISBE_YOUTUBE: 'https://www.youtube.com/@REDISBE',
    ISBE_X: 'https://x.com/REDISBE',
    BUNDLE_ENABLED: false,
    DFT_CATALOG_ID: '',
    MAX_FILE_SIZE:3145728,
    SCOPE: "openid profile email",
    RESPONSE_TYPE: 'code',
    AUTHORITY: "https://idp.dev.cloud-w.envs.redisbe.com/auth/realms/dev-isbe",
    REDIRECT_URL: "https://catalog.dev.cloud-w.envs.redisbe.com",
    POST_LOGIN_ROUTE: '/dashboard'
};
