
export const environment = {
    DEV_ACCESS_TOKEN: "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICItckxwSkhNVkhCSUQ0Q2FRX0dsTjhFTEprQ0tYMUJWUzhMTzd6enU1cTFVIn0.eyJleHAiOjE3NzkxMDM1ODQsImlhdCI6MTc3OTA5OTk4NCwiYXV0aF90aW1lIjoxNzc5MDk5OTU5LCJqdGkiOiJvbnJ0YWM6NGJkZjY0NWQtNTEwZC1hMTZlLTk4ZGQtOGZiOWZhYjFkNDY5IiwiaXNzIjoiaHR0cHM6Ly9pZHAuZGV2LmNsb3VkLXcuZW52cy5yZWRpc2JlLmNvbS9hdXRoL3JlYWxtcy9kZXYtaXNiZSIsImF1ZCI6WyJpc2JlLXBvcnRhbC1kZXYiLCJhY2NvdW50Il0sInN1YiI6ImMyYmI2ZWFjLTk2NDMtNDYwYS04Y2U0LWQxODI5NDZiNDE5OCIsInR5cCI6IkJlYXJlciIsImF6cCI6Imh0dHBzOi8vY2F0YWxvZy5pc2Jlb25ib2FyZC5jb20iLCJzaWQiOiI2ZTg2YTNjYy0zYTAyLTgyM2YtYmY2MS0wNmM1ODUwNmY1MWEiLCJhY3IiOiIwIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHBzOi8vY2F0YWxvZy5kZXYuY2xvdWQtdy5lbnZzLnJlZGlzYmUuY29tIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLWRldi1pc2JlIiwib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIG9yZ2FuaXphdGlvbiBlbWFpbCBwcm9maWxlIiwidXNlcl9pZGVudGlmaWVyIjoiMTIzNDUxMDBKIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm9yZ2FuaXphdGlvbiI6IkFDTUVTIiwibmFtZSI6Ikx1a2UgU21pdGgiLCJvcmdhbml6YXRpb25faWRlbnRpZmllciI6IlZBVEVTLUcwMDAzNjA1MCIsInByZWZlcnJlZF91c2VybmFtZSI6ImFsYmEubG9wZXpAYWx0aWEuZXMiLCJwb3dlciI6W3sidHlwZSI6Im9yZ2FuaXphdGlvbiIsImFjdGlvbiI6WyIqIl0sImRvbWFpbiI6IklTQkUiLCJmdW5jdGlvbiI6Ik1hbmFnZW1lbnQifSx7InR5cGUiOiJvcmdhbml6YXRpb24iLCJhY3Rpb24iOlsiKiJdLCJkb21haW4iOiJJU0JFIiwiZnVuY3Rpb24iOiJIZWxwZGVzayJ9LHsidHlwZSI6Im9yZ2FuaXphdGlvbiIsImFjdGlvbiI6WyIqIl0sImRvbWFpbiI6IklTQkUiLCJmdW5jdGlvbiI6IkZhdWNldCJ9LHsidHlwZSI6Im9yZ2FuaXphdGlvbiIsImFjdGlvbiI6WyIqIl0sImRvbWFpbiI6IklTQkUiLCJmdW5jdGlvbiI6IldpemFyZCJ9LHsidHlwZSI6Im9yZ2FuaXphdGlvbiIsImFjdGlvbiI6WyIqIl0sImRvbWFpbiI6IklTQkUiLCJmdW5jdGlvbiI6Ik5vdGFyaXphdGlvbiJ9LHsidHlwZSI6Im9yZ2FuaXphdGlvbiIsImFjdGlvbiI6WyIqIl0sImRvbWFpbiI6IklTQkUiLCJmdW5jdGlvbiI6Ik5vdGlmaWNhdGlvbnMifSx7InR5cGUiOiJvcmdhbml6YXRpb24iLCJhY3Rpb24iOlsiKiJdLCJkb21haW4iOiJJU0JFIiwiZnVuY3Rpb24iOiJJZGVudGl0eSJ9LHsidHlwZSI6Im9yZ2FuaXphdGlvbiIsImFjdGlvbiI6WyIqIl0sImRvbWFpbiI6IklTQkUiLCJmdW5jdGlvbiI6IkVucm9sbG1lbnQifSx7InR5cGUiOiJvcmdhbml6YXRpb24iLCJhY3Rpb24iOlsiRXhlY3V0ZSJdLCJkb21haW4iOiJJU0JFIiwiZnVuY3Rpb24iOiJPbmJvYXJkaW5nIn1dLCJnaXZlbl9uYW1lIjoiTHVrZSIsInVzZXIiOiJMdWtlIFNtaXRoIiwiZmFtaWx5X25hbWUiOiJTbWl0aCIsImVtYWlsIjoiYWxiYS5sb3BlekBhbHRpYS5lcyJ9.G_gW7vuoh6aiYqyahl-AMkn3WYmB1uuN8df-a2t8fOdqR14gOMiwV081Jx22JcGu7CpS2X6sW8B28xJOBS3_L7cpMo0Jb7w5uCAIaC7YmkzN2HBZwRxnZS1ABUXYpcPnr7_-2-MIm_OkADD87PI8jQs9suIHn7thTNeBPBW4I6BOu6fLHglNLvkQ_BUVSsTI1VIhq6xmhdXte4OZd9cR_QnzikCwGUzD1U_uj42fHcM0dUKvVtOM8kHGnRBBWDeqdYQPq7nzsDoUgUQcmKp-bp38JV4C4R-0AsJDJ1O6TzDpRkBraYUvFXgzMWGz9PtdY1mQ4yYWQOq9wazpbyi1ww",
    BASE_URL: 'https://tmf.dev.portal.redisbe.com/tmf-api/',
    FOUNDATION_ID: 'VATES-G87936159',
    locale: 'es-ES',
    PRODUCT_CATALOG_MANAGEMENT_URL: 'productCatalogManagement/v4',
    PARTY_URL: 'party/v4',
    PAYMENT_URL: '',
    ISBE_CATALOGUE: true,
    LEGACY_PREFIX: '',
    ORGANIZATION: '/organization',
    INDIVIDUAL: '/individual',
    PRODUCT_CATALOG: '/catalog',
    SERVICE: '/service',
    RESOURCE: '/resource',
    PRODUCT_SPEC: '/productSpecification',
    SERVICE_SPEC: '/serviceSpecification',
    RESOURCE_SPEC: '/resourceSpecification',
    ACCOUNT: '/account',
    SHOPPING_CART: '/shoppingCart',
    INVENTORY: '/inventory',
    PRODUCT_ORDER: '/ordering',
    CHARGING: '/charging',
    BILLING: '/billing',
    CUSTOMER_BILLING:'/appliedCustomerBillingRate',
    CONSUMER_BILLING_URL: '',
    PRODUCT_LIMIT: 6,
    CATALOG_LIMIT: 8,
    INVENTORY_LIMIT: 6,
    INVENTORY_RES_LIMIT: 6,
    INVENTORY_SERV_LIMIT: 6,
    PROD_SPEC_LIMIT: 6,
    USAGE_SPEC_LIMIT: 6,
    ORDER_LIMIT: 1000,
    CATEGORY_LIMIT: 100,
    INVOICE_LIMIT: 100,
    SIOP: false,
    TAX_RATE: 20,
    AUTH_MODE: 'oidc',
    SIOP_INFO: {
        enabled: true,
        isRedirection: true,
        pollPath: "",
        pollCertPath: "",
        clientID: "https://catalog.isbeonboard.com",
        callbackURL: "http://localhost:4200/dashboard",
        verifierHost: "https://verifier.dome-marketplace-sbx.org",
        verifierQRCodePath: '/oidc/authorize',
        requestUri: "https://verifier.dome-marketplace-sbx.org/oid4vp/auth-request"
    },
    MATOMO_TRACKER_URL: "",
    MATOMO_SITE_ID: "",
    TICKETING_SYSTEM_URL: "",
    KNOWLEDGE_BASE_URL: "",
    KB_ONBOARDING_GUIDELINES_URL: "",
    KB_GUIDELNES_URL:"",
    REGISTRATION_FORM_URL: "https://onboard-dev.redisbe.com/register",
    SEARCH_ENABLED: false,
    PURCHASE_ENABLED: false,
    ISBE_TRUST_LINK: "",
    ISBE_ABOUT_LINK: 'https://redisbe.com/',
    ISBE_REGISTER_LINK: 'https://onboard-dev.redisbe.com/register',
    ISBE_PUBLISH_LINK:'',
    ISBE_LINKEDIN: 'https://www.linkedin.com/company/redisbe/posts/?feedView=all',
    ISBE_YOUTUBE: 'https://www.youtube.com/@REDISBE',
    ISBE_X: 'https://x.com/REDISBE',
    BUNDLE_ENABLED: false,
    DFT_CATALOG_ID: '',
    MAX_FILE_SIZE:3145728,
    SCOPE: "openid profile email",
    RESPONSE_TYPE: 'code',
    AUTHORITY: "https://idp.dev.cloud-w.envs.redisbe.com/auth/realms/dev-isbe",
    REDIRECT_URL: "https://catalog.dev.cloud-w.envs.redisbe.com",
    POST_LOGIN_ROUTE: '/dashboard'
};
