export const environment = {
    BASE_URL: 'http://localhost:8004',
    PAYMENT_URL: 'https://payment.dome-marketplace-sbx.org',
    LEGACY_PREFIX: '',
    //API_PORT: 8632,
    //API_PORT: 8004,
    //API ENDPOINTS
    PRODUCT_CATALOG: '/catalog',
    SERVICE: '/service',
    RESOURCE: '/resource',
    PRODUCT_SPEC: '/productSpecification',
    SERVICE_SPEC: '/serviceSpecification',
    RESOURCE_SPEC: '/resourceSpecification',
    ACCOUNT: '/account',
    SHOPPING_CART: '/shoppingCart',
    INVENTORY: '/inventory',
    PRODUCT_ORDER: '/ordering',
    CHARGING: '/charging',
    BILLING: '/billing',

    CUSTOMER_BILLING:'/appliedCustomerBillingRate',
    CONSUMER_BILLING_URL: 'http://localhost:8640',
    //API PAGINATION
    PRODUCT_LIMIT: 6,
    CATALOG_LIMIT: 8,
    INVENTORY_LIMIT: 6,
    INVENTORY_RES_LIMIT: 6,
    INVENTORY_SERV_LIMIT: 6,
    PROD_SPEC_LIMIT: 6,
    USAGE_SPEC_LIMIT: 6,
    ORDER_LIMIT: 1000,
    CATEGORY_LIMIT: 100,
    INVOICE_LIMIT: 100,
    SIOP: false,
    TAX_RATE: 20,
    CHAT_API: 'https://85.215.243.214:5000/predict',
    SIOP_INFO: {
        enabled: false,
        isRedirection: false,
        pollPath: "",
        pollCertPath: "",
        clientID: "",
        callbackURL: "",
        verifierHost: "",
        verifierQRCodePath: "",
        requestUri: ""
    },
    MATOMO_TRACKER_URL: "",
    MATOMO_SITE_ID: "",
    TICKETING_SYSTEM_URL: "",
    KNOWLEDGE_BASE_URL: "",
    KB_ONBOARDING_GUIDELINES_URL: "",
    KB_GUIDELNES_URL:"",
    REGISTRATION_FORM_URL: "",
    SEARCH_ENABLED: true,
    PURCHASE_ENABLED: false,
    ISBE_TRUST_LINK: "https://dome-certification.dome-marketplace.org",
    ISBE_ABOUT_LINK: '',
    ISBE_REGISTER_LINK: '',
    ISBE_PUBLISH_LINK:'',
    ISBE_LINKEDIN: '',
    ISBE_YOUTUBE: 'https://www.youtube.com/@REDISBE',
    ISBE_X: 'https://x.com/REDISBE',
    BUNDLE_ENABLED: false,
    DFT_CATALOG_ID: '',
    MAX_FILE_SIZE:3145728,
};
